DROP TABLE IF EXISTS moving;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS organizations;

CREATE TABLE IF NOT EXISTS organizations (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name      VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name              VARCHAR(100) NOT NULL,
  organization_id   BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name              VARCHAR(100) NOT NULL,
  reporting         BOOLEAN NOT NULL,
  position          VARCHAR(50) NOT NULL,
  email             VARCHAR(50) NOT NULL UNIQUE,
  password          VARCHAR(50) NOT NULL,
  role              VARCHAR(10) NOT NULL,
  organization_id   BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS departments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name              VARCHAR(100) NOT NULL,
  address           VARCHAR(200) NOT NULL,
  organization_id   BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  category_id       BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  name              VARCHAR(100) NOT NULL,
  description       VARCHAR(1000) NOT NULL,
  serviceable       BOOLEAN NOT NULL,
  inv_number        VARCHAR(50),
  created           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  finished          TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS moving (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  moving_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id               BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  from_owner_id         BIGINT REFERENCES users(id) ON DELETE CASCADE,
  to_owner_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  from_department_id    BIGINT REFERENCES departments(id) ON DELETE CASCADE,
  to_department_id      BIGINT NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  description           VARCHAR(1000)
);